# Generated by Django 5.0.6 on 2024-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='recommended_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
